### ISSUE TITLE
Missing offline message

### ISSUE THREAD

**Issue by CocaCola183** [mcollina/mosca#210]
broker:
var ascoltatore = {
    type: 'zmq',
    json: false,
    zmq: require("zmq"),
    port: "tcp://127.0.0.1:33333",
    controlPort: "tcp://127.0.0.1:33334",
    delay: 10
};

var moscaSettings = {
    port: 1883,
    backend: ascoltatore,
    persistence: {
        factory: mosca.persistence.Redis
    }
};

var server = new mosca.Server(moscaSettings);
...

client1:
var mqtt = require('mqtt');
client = mqtt.createClient(1883, 'localhost');
client.subscribe('test1',{qos:1});
client.on('message', function (topic, message, packet) {
    console.log(message);
});

client2:
var mqtt = require('mqtt');
client = mqtt.createClient(1883, 'localhost');

client.publish('test1','I am client2-1.',{qos:1,retain:true});
client.publish('test1','I am client2-2.',{qos:1,retain:true});
client.publish('test1','I am client2-3.',{qos:1,retain:true});
client.publish('test1','I am client2-4.',{qos:1,retain:true});

client.on('message', function (topic, message, packet) {
    console.log(message);
});

run server--->run client2--->run client1,but the client1 can only get "I am client2-4.",that is,I can only get the last offline message not all , how can I get all of them? Is there any problem with my use of zmq or redis ? Looking forward reply ! Thanks!

**Comment by mcollina** [comment]
Offline mesages works only if you specify a clientId and clean: false.
Also, you nees to run client1 before client2, and then kill it. Then run
client1. After you restart client1, it should receive the messages.


The current solution is kind-of working because of the retain flag, which
forwards the last message published to the given topic when a client
subscribes.
Il giorno lun 5 gen 2015 alle 02:22 Kivi <notifications@github.com> ha
scritto:

**Comment by CocaCola183** [comment]
Thanks very much for your help and understanding of my poor English!
