### ISSUE TITLE
IP Address.

### ISSUE THREAD

**Issue by PritamUpadhyay** [mcollina/mosca#297]
Is there any way to know the **IP Address** of connected _mqtt client_ in **mosca**?

**Comment by codebeautiful** [comment]
me too, thanks

**Comment by mcollina** [comment]
This is a nice feature, however it is not standardized. Look __deep__ into `client.conn`, at some point there is the underlining stream, and from there you should be able to access that information.
The problem is that access to it is not standardized across TCP/TLS and WebSockets, so you would have to do it.

See https://nodejs.org/api/net.html#net_class_net_socket for TCP/TLS (they honor the same interface).
It would be nice if [websocket-stream](http://npm.im/websocket-stream) honored the same interface, too.

**Comment by PritamUpadhyay** [comment]
Got it.
Thanks.

**Comment by parthmehta** [comment]
@PritamUpadhyay  Where exactly did you find the IP address of the client that is connected ?

**Comment by parthmehta** [comment]
@PritamUpadhyay  Thanks for a quick reply. 

I got in in the clientConnected event as follows : 

```
sever.on('clientConnected', function(client) {
   console.log(client.connection.stream.remoteAddress)
})
```

**Comment by PritamUpadhyay** [comment]
@parthmehta 👍 
You're Welcome. :)

**Comment by anani112** [comment]
client.connection.stream.remoteAddress works great! however I'm in the situation where mosca is running behind a load balancer (AWS elastic load balancer - ELB) in which case client.connection.stream.remoteAddress returns the IP address of the load balancer instead of the original client. I found out that ELB uses the proxy protocol and on a regular node/express.js application you extract the original IP address from the TCP packet using a library like this one: https://github.com/racker/node-proxy-protocol
Does mosca expose the raw TCP packet needed to extra the original IP address? Any pointers about how to approach this problem? Thanks

**Comment by mcollina** [comment]
At the moment no. Check out aedes: https://github.com/mcollina/aedes. You will have access to the stream there.

**Comment by anani112** [comment]
Sounds good. I'll play with aedes and see where that takes me. Thanks!

**Comment by mcollina** [comment]
Feel free to send an example or a PR there, it might be something a lot of people will be interested in.

**Comment by syberkitten** [comment]
It should be very useful since part of the MQTT Authentication
might involve black listing certain IP's.

**Comment by KevinNovak** [comment]
Has anything changed since your comment in 2016? I'm always getting undefined for `client.connection.stream.remoteAddress`

**Comment by KevinNovak** [comment]
Ignore my comment... The above works, I was just dumb using Nginx and forgot to forward the real IP address.
