### ISSUE TITLE
Persistence MongoDB

### ISSUE THREAD

**Issue by Whitebeard86** [mcollina/mosca#333]
Hello,

Somehow when I add the MongoDB persistence specification to the config file, the server doesn't startup (but it doesn't show any errors, can I do something to show them?)
```
var mongoSettings = {
	type: 'mongo',
	url: 'mongodb://localhost:27017/mqtt',
	pubsubCollection: 'mqtt',
	mongo: {}
}

var settings = {
	port: 1883,
	http: {
		port: 443,
		bundle: true,
		static: './'
	},
	backend: mongoSettings,
	persistence: {
		factory: mosca.persistence.Mongo,
		url: 'mongodb://localhost:27017/mqtt'
	}
};
```

On the MongoDB side, I've installed it and it's running. I've used the client to create the db 'mqtt'. Do I have to do any extra configuration?

Thanks.
J.

**Comment by ccravens** [comment]
What version of Mosca are you running? I had this problem too, and it was due to an error in one of the Mosca dependencies, I forget which one and I forget which version. However, with the latest versions of Mosca (1.2.0 right now) this problem should be fixed. I am successfully running our Mosca server with a MongoDB backend.

**Comment by mcollina** [comment]
I think this is a really old issue.
Let me close it for now, I hope @Whitebeard86 has fixed his problems.
