### ISSUE TITLE
publish function is not working on mongodb 3.0.4

### ISSUE THREAD

**Issue by tuanquynet** [mcollina/mosca#337]
I have tested it working well on mongodb 3.0.1, but when I upgrade to mongodb 3.0.4 the publish method is not working.

**Comment by denistiago** [comment]
I have tested on mongodb 3.0.5, and it is also not working.

**Comment by mcollina** [comment]
@sahilsk if you want to investigate this too, it would be awesome!

**Comment by denistiago** [comment]
@sahilsk my issue was related to authentication/authtorization. 
I was running the mongo example with an authenticated mongo database. 

var mongoUrl = 'mongodb://mqtt:mqtt@localhost/mqtt'

i found the error on mongo logs: 
2015-09-01T17:37:35.419-0300 I ACCESS   [conn1462] Unauthorized not authorized on ascoltatori to execute command { dbStats: true }

when i turn off authentication, it works like a charm.

**Comment by sahilsk** [comment]
@denistiago 
it seems more of a mongodb auth issue.  Please confirm db roles.  For me role "dbOwner" worked.

```
use mqtt;
db.getUser('mqtt')
{
	"_id" : "mqtt.mqtt",
	"user" : "mqtt",
	"db" : "mqtt",
	"roles" : [
		{
			"role" : "dbOwner",
			"db" : "mqtt"
		}
	]
}
```

**Comment by sahilsk** [comment]
On second look it's a problem.  Sorry @denistiago  for misunderstanding.

@mcollina  
In ascoltatori wrong argument is given. `that.db.db(that._pubsubCollection).stats(...)` 
Isn't it should be db name instead of collection?
In ascoltatori examples db name and collection name are same i.e `ascoltatori` . Probably that's why it missed tests.

https://github.com/mcollina/ascoltatori/blob/6ebf033557c7ef7a7c23e70a309b188ba8eddcb3/lib/mongo_ascoltatore.js#L194-L195

``` js

  var reconnect = function () {
    debug('handleCursorClosed -> Wait for the database to be connected...');
    that.db.db(that._pubsubCollection).stats({}, function (err, stats) {
      var success = true;
      if (err) {
...
```

**Comment by mcollina** [comment]
It might be, would you like to investigate and in case send a pull request?

**Comment by sahilsk** [comment]
sure.. let me try

**Comment by sahilsk** [comment]
@mcollina   here is the PR
 https://github.com/mcollina/ascoltatori/pull/130

**Comment by mcollina** [comment]
Fixed since some time ago :)
