### ISSUE TITLE
Can edit message before mosca server publish a again to client ?

### ISSUE THREAD

**Issue by tinamore** [mcollina/mosca#344]
Hi
Can i modify message before mosca server publish again to client subscribed ?
Thanks.

**Comment by mcollina** [comment]
No, it cannot.

**Comment by tinamore** [comment]
Ok, thanks for response.

**Comment by behrad** [comment]
I need a `cancel` or `isNew` flag on published messages, for cases like multi device message delivery. (user opens device A and receives message, on device B I want to update the to be published message with some flag like `isNotNew` or `isSeen` so that client handles that differently.
In some cases we may also want to cancel an offline message :)

Can you propose any method to achieve this @mcollina ?
