### ISSUE TITLE
Topic hierachies

### ISSUE THREAD

**Issue by vallettea** [mcollina/mosca#348]
Hello,

thanks for your amazing job on mqtt.
I read on mqtt specs that topics are hierarchical (meaning  `/command/init` will be sent to all people subscribed to `command` as well as those subscribed only to `command/init`)

It seems that mosca/mqtt does not support this feature. Am-I missing something ?
Best

**Comment by mcollina** [comment]
That's not true. MQTT do not have that feature at all. You need to look at `#` and `+` subscriptions.

**Comment by vallettea** [comment]
Can you provide an example or at least a link where I can look at this ?

**Comment by vallettea** [comment]
Can you provide an example or at least a link where I can look at this ?

**Comment by psorowka** [comment]
Subscriptions refer only to the specified topic, e.g. when one client subscribes to `command`, it will only receive messages pushed to `command` and not `command/init` 

However, you can include wildcards (`#` and `+`) when subscribing, thus subscribing to `command/#` would allow you to receive also messages from `command/init` or even `command/foobar/init`. When you want a wildcard that matches only one layer of hierarchy, use `+` instead of `#`

**Comment by mcollina** [comment]
Thanks Peter
Il giorno ven 18 set 2015 alle 19:20 Peter Sorowka <notifications@github.com>
ha scritto:

**Comment by vallettea** [comment]
thanks a lot for the explanation.
