### ISSUE TITLE
Host not reachable in LAN.

### ISSUE THREAD

**Issue by roccomuso** [mcollina/mosca#366]
I'm executing Mosca on a Windows 10 pc (Wit local Ip address 192.68.1.6), using Mosquitto as Parent Broker, right down you can see my settings (host is 127.0.0.1) and I just discovered that when i wanna communicate with the broker from another pc in the LAN through mosquitto or any other mqtt client, using the host 192.168.1.6 it doesn't work (host is 127.0.0.1 in the broker's settings), but  using 192.168.1.6 in broker's settings make it works.

    var pubsubsettings = {
      type: 'mqtt',
      json: false,
      mqtt: require('mqtt'),
      host: '127.0.0.1',
      port: 1883
    };
    
    var settings = {
      port: 1883,
      backend: pubsubsettings
    };

    var server = new mosca.Server(pubsubsettings);

Why my broker is not reachable from 192.168.1.6 (LAN Ip address) if i use in the broker's settings the 127.0.0.1 address?

**Comment by dennisdegreef** [comment]
This is because `127.0.0.1` is also known as the loopback IP-address. It binds to the virtual local adapter on your machine.

This means that since you are binding port `1883` on `127.0.0.1`, you can only reference that service from that machine.

If you were to bind on `192.168.1.6`, you would be able to reach it from the LAN network. If you don't want to bind on all interfaces, you could probably also use `0.0.0.0`.

I hope this helps you with your problem, I don't this this is an issue related to mosca itself.

**Comment by roccomuso** [comment]
But why on the classical web server, listening on 127.0.0.1:80 make the pc reachable even from (for example) 192.168.1.6:80 ?

What i gotta do to have my mqtt server listening on both 127.0.0.1 (for debugging purpose) and the classical 192.168.1.6?

**Comment by mcollina** [comment]
You should omit the `host` property in your configuration.
