### ISSUE TITLE
Message Expiry

### ISSUE THREAD

**Issue by behrad** [mcollina/mosca#384]
MQTT looks not supporting this but can we support a sort of message expiry for qos>0 messages? That means if a client is not connected in time, Mosca will drop it. 

P.S. At first glance this looks costy for different persistence engines, and can be implemented by applications in client side.

**Comment by mcollina** [comment]
What does that mean? I would put these in the v2/aedes line.

message expirations will not be present there (as of now).

**Comment by psorowka** [comment]
This is absolutely an important topic. However it is more something for ascoltatori, than for mosca, because it heavily depends on the backend. When the backend is memory or a self hosted db (redis, mongo, leveldb) it could be possible that broker storage runs full when a client subscribes with clean session 0 to heavily used topics. If the backend is another mqtt broker or rabbitmq I figure the problem is on their side.

IMHO we speak primarily about session expiration here, because if a server has a session associated with a client, it is required to forward all offline packets. Forwarding only parts of the offline packets could lead to unexpected results. 

The spec states: 

> A Session MUST last at least as long it has an active Network Connection

So we are free in deciding when to expire the session. It could be difficult, though, to decide when to delete the according stored packets. Possibly the easiest solution would be to assign the expiry date of the oldest session to any stored packets.

**Comment by mcollina** [comment]
> When the backend is memory or a self hosted db (redis, mongo, leveldb) it could be possible that broker storage runs full when a client subscribes with clean session 0 to heavily used topics and never comes back.

It's not ascoltatori, it's the persistence layer.

We need a cleanup strategy that works across persistences, but again this is a thing for v2/aedes.

**Comment by psorowka** [comment]
right, the persistence layer in ascoltatori, isn't it :) 

agreed, should be for aedes. do you have some internal issue check list for aedes?

**Comment by mcollina** [comment]
There is a big todo list in the README, open an issue there.

**Comment by behrad** [comment]
:+1:
