### ISSUE TITLE
Cluster-aware Redis backend

### ISSUE THREAD

**Issue by behrad** [mcollina/mosca#441]
#428 showed a real bottleneck to us now, and I am thinking a simple optimization which if could use Redis Cluster to scale to > 500000 and Millions of subscriptions.  

Interesting points for optimization are two fold:

1) Current Redis backend in Mosca (Aedes' one should be https://github.com/mcollina/mqemitter-redis if not wrong) is using pub/sub to inform all nodes about all subscriptions, so each sub is replicated in all other mosca instances memories (all being stored in a single shared redis instance), this way as #428 states, node startup is slow even in small numbers of subs even after local optimizations.
However, redis backend of each mosca/aedes instance could use a multi node redis-cluster, with each instance only keeping it's local subs in memory, and upon receiving a publish, local node can publish on a backend-convented internal topic, which all other broker instances are subscribed. This way all nodes will catch the publish, and only the nodes containing matched subscriptions in-memory will forward the message. Feels distributing both subs & message delivery work load.
Every instance could hash-tag it's own sub keys (if redis node locality needed). 
You now about the internals & code @mcollina , Can you please argue about the correctness of above?

I also don't know about the method of Aedes Cluster support roadmap.

2) The internal in-memory representation of subscriptions (currently [Qlobber](https://github.com/davedoesdev/qlobber) trie), discussed in #428

**Comment by mcollina** [comment]
Regarding 1: yes to the state of things, and to an alternative implementation of Redis pub/sub system. The main difference is if your application is built around having lots of "silent" subscribers (subscribers that seldom receives data), or you are sending a lot of data to those subscribers. The current implementation trades off startup speed for being able to handle lots of moving data. The one you propose will use a broadcast - so every node will receive every message published (like MongoDB does currently). That will trade off message throughput for the number of subscribers. 

As all the things Aedes, it will be done when it will be done. However, I might have a proof of concept for your use case sooner rather than later (distributed pub/sub broker based on Gossip network and AP/CAP).

**Comment by mcollina** [comment]
What is your topic structure @behrad? `device/{ID}` or similar?

**Comment by behrad** [comment]
> What is your topic structure @behrad? device/{ID} or similar?

Topics are 5 levels long: 
1) `app/{ID}/user/{ID}/{channel}`  are user level topics, each user can subscribe to multiple channels...
2) `app/{ID}/user/public/{channel}` are public topics, which all users are subscribed to

**Comment by mcollina** [comment]
how much cardinality have you got related to those ids?

**Comment by behrad** [comment]
Complicated. Depends on the scale & scenarios...
totally you can imagine around 50 apps, each containing 50,000 to 1 million users, each user <10 topics...

However some rules/scenarios are:

1) each user internally is subscribed to 3 native topics, so system at-least will have 3*(a few millions) topics when total users are in millions. (currently reaching to 100,000 users will catch the above startup bottleneck) let alone the memory usage of each broker instance, which I've not had enough chance to stress test that.

2) a single app may contain a million user of each subscribing to <10 topics

**Comment by mcollina** [comment]
Should be fixed in v2.0.0.
It would be awesome if you could send a dockerized example :).
