### ISSUE TITLE
Mongo adapter crashes on windows - xp 

### ISSUE THREAD

**Issue by gbaumgart** [mcollina/mosca#463]
Hi,
I am already in touch with the mongo guys but they say it should work all properly with a Mongo - 2.6 server, which i use and it runs fine.

It crashes in mongodb/lib/server.js at line 242 with error unknow. Do you have any pointer for us? We only passed the minimal options to the mosca setup and it runs fine on all other platforms, just not windows-xp (too many users and hardware which cant get updated).

**Comment by mcollina** [comment]
What's your use case? Why do you need to support windows xp? It's not even supported by Microsoft. 

Which version of node are you using?

**Comment by gbaumgart** [comment]
hi, thanks for popping up. There is is still too much hardware which we can't update. Or you expect us to teach people to throw 3000+$ laptops in the trash when they are working fine? Btw, windows-7+ isn't option, even if there are hardware drivers and believe me, there are a lot of xp users, including our self. 

Anyhow, I could isolate and figure now that the problem is on mongo's side. Not yours. Gonna close this.

**Comment by gbaumgart** [comment]
The guys from Mongo-DB fixed it without any discussion

1.  https://github.com/mongodb/node-mongodb-native/commit/ed3a7ce15e393be65a0010ab9317f7fbcbdb5875
2. actual issue: https://jira.mongodb.org/browse/NODE-697

**Comment by mcollina** [comment]
They definitely have the resources for doing so, kudos to them for doing it that quickly. Windows XP is definitely not supported here, but I'm glad this works fine for you. Please send over any PR to keep it working, if you like.

Just to point out that node 6 does not support Windows Vista or earlier, and you might soon need to make a decision when to stop supporting it: April 2018 is when node v4 will become unsupported, and probably sooner (due to library compatibilities).
Plus, running an operating system without security patches is definitely a security risk, which I will not recommend to anyone.

**Comment by gbaumgart** [comment]
ok, thanks. i am aware about these points but I not sure how much mean it has to all the countries who re-use our hardware from the western world. I know myself around 5 waste collectors here in Barcelona, sending pre-2010 hardware to Africa.... So at least, I made sure that I don't contribute in these wasteful practices. I own myself 2 good laptops which i can't update to win7 or linux, I am very happy to make them valuable with my software ;-)
