### ISSUE TITLE
About npm dependencies

### ISSUE THREAD

**Issue by jsdario** [mcollina/mosca#466]
> This is intended to be a question / enhancement for the long future discussion since I really appreciate this package and the work that has been performed behind.

Currently I use mosca only over http/https, however it has a huge part of its dependency tree on other publisher/subscriber mechanisms.

http://npm.anvaka.com/#/view/2d/mosca

Wouldn't it make more sense to change to a plugin approach? As when `express` did away with many other packages (like body or cookie parser).

I guess it would make a lot of sense to just fork and go with a lighter implementation for our case, which would be rather simple.

**Comment by mcollina** [comment]
That's the approach I am following with the "rewrite" of Mosca, https://github.com/mcollina/aedes.
At some point in the future mosca will just be the collection of all the aedes related modules.
If you want to help there, you are welcome to test and report issues!

BTW, you will need most of the modules anyway, because the MQTT logic is the same. You might not need redis, amqp, mongo or zmq, but that's it.
