### ISSUE TITLE
Why MQTT server can receive its own publish message

### ISSUE THREAD

**Issue by VegeChou** [mcollina/mosca#480]
I want use MQTT server to receive message from client1 and forward to another client2.
But when I called **Server.Publish**, its own **Published Event** could receive this message and the code is going into loop.

My server code:

```
server.on('published', function(packet, client) {
  console.log(packet);

  server.publish({
    topic: 'uplink',
    payload: '0123456789'
  }, function() {
    console.log('done!');
  });
});
```

Logs in console is below :

```
{ topic: 'uplink',
  payload: '0123456789',
  messageId: 'HkQhW2-b7G7',
  qos: undefined,
  retain: undefined }
done!
{ topic: 'uplink',
  payload: '0123456789',
  messageId: 'rk42-3bWmfm',
  qos: undefined,
  retain: undefined }
done!
{ topic: 'uplink',
  payload: '0123456789',
  messageId: 'HySnbn-W7MX',
  qos: undefined,
  retain: undefined }
done!
{ topic: 'uplink',
  payload: '0123456789',
  messageId: 'ryUnbhZ-Xz7',
  qos: undefined,
  retain: undefined }
done!

```

**Comment by mcollina** [comment]
Because we can always write a `while(true) {}` loop in any programming language :). The actual answer is that I don't know, but there is no way to tell the difference.

Jokes apart, the actual hook you want to use is `authorizePublish`, which is executed _before_ publish and thus will not lead to an infinite loop.
