### ISSUE TITLE
MQTTjs Websocket Cordova

### ISSUE THREAD

**Issue by japita-se** [mcollina/mosca#570]
Is it possible to user MQTTjs (browserMQTT) in a packed cordova webapp?
I tried to port the web page I made by using cordova, but it seems that the websockets not work.
Is it a problem of the cordova webkit?

**Comment by gafopi** [comment]
@japita-se It is definitely possible to use MQTT over WebSockets with Cordova. If I had to guess, your issue is probably related to Cordova's Content Security Policy. 

Make sure you whitelist the broker url with the correct port number. This [plugin](http://cordova.apache.org/docs/en/6.x/reference/cordova-plugin-whitelist/index.html#page-toc-source) could help. Let me know if that fixes your problem.

**Comment by keanuyaoo** [comment]
Cordova don't include webkit  !  It rely on mobile phone OS;
[CanIUse](http://caniuse.com/#search=websocket) says  IOS>=7.1 & Android >=4.4 support websocket;
Make sure your os version;
If you  plan to support low version os , follow Crosswalk ,  or code cordova plugin with native code to connect mosca;

**Comment by ameykshirsagar** [comment]
@japita-se I have created a native based plugin for Cordova [here](https://github.com/arcoirislabs/cordova-plugin-mqtt)
